//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/upgrade/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Msg defines the upgrade Msg service.
///
/// Usage: instantiate `Cosmos_Upgrade_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Upgrade_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func softwareUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse>

  func cancelUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgCancelUpgrade,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse>
}

extension Cosmos_Upgrade_V1beta1_MsgClientProtocol {
  public var serviceName: String {
    return "cosmos.upgrade.v1beta1.Msg"
  }

  /// SoftwareUpgrade is a governance operation for initiating a software upgrade.
  ///
  /// Since: cosmos-sdk 0.46
  ///
  /// - Parameters:
  ///   - request: Request to send to SoftwareUpgrade.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func softwareUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSoftwareUpgradeInterceptors() ?? []
    )
  }

  /// CancelUpgrade is a governance operation for cancelling a previously
  /// approved software upgrade.
  ///
  /// Since: cosmos-sdk 0.46
  ///
  /// - Parameters:
  ///   - request: Request to send to CancelUpgrade.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cancelUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgCancelUpgrade,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelUpgradeInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Upgrade_V1beta1_MsgClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Upgrade_V1beta1_MsgNIOClient")
public final class Cosmos_Upgrade_V1beta1_MsgClient: Cosmos_Upgrade_V1beta1_MsgClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.upgrade.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Upgrade_V1beta1_MsgNIOClient: Cosmos_Upgrade_V1beta1_MsgClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.upgrade.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Msg defines the upgrade Msg service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Upgrade_V1beta1_MsgAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func makeSoftwareUpgradeCall(
    _ request: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse>

  func makeCancelUpgradeCall(
    _ request: Cosmos_Upgrade_V1beta1_MsgCancelUpgrade,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Upgrade_V1beta1_MsgAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Upgrade_V1beta1_MsgClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSoftwareUpgradeCall(
    _ request: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSoftwareUpgradeInterceptors() ?? []
    )
  }

  public func makeCancelUpgradeCall(
    _ request: Cosmos_Upgrade_V1beta1_MsgCancelUpgrade,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelUpgradeInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Upgrade_V1beta1_MsgAsyncClientProtocol {
  public func softwareUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSoftwareUpgradeInterceptors() ?? []
    )
  }

  public func cancelUpgrade(
    _ request: Cosmos_Upgrade_V1beta1_MsgCancelUpgrade,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCancelUpgradeInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Upgrade_V1beta1_MsgAsyncClient: Cosmos_Upgrade_V1beta1_MsgAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'softwareUpgrade'.
  func makeSoftwareUpgradeInterceptors() -> [ClientInterceptor<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse>]

  /// - Returns: Interceptors to use when invoking 'cancelUpgrade'.
  func makeCancelUpgradeInterceptors() -> [ClientInterceptor<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse>]
}

public enum Cosmos_Upgrade_V1beta1_MsgClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Msg",
    fullName: "cosmos.upgrade.v1beta1.Msg",
    methods: [
      Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade,
      Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade,
    ]
  )

  public enum Methods {
    public static let softwareUpgrade = GRPCMethodDescriptor(
      name: "SoftwareUpgrade",
      path: "/cosmos.upgrade.v1beta1.Msg/SoftwareUpgrade",
      type: GRPCCallType.unary
    )

    public static let cancelUpgrade = GRPCMethodDescriptor(
      name: "CancelUpgrade",
      path: "/cosmos.upgrade.v1beta1.Msg/CancelUpgrade",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Upgrade_V1beta1_MsgTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Upgrade_V1beta1_MsgTestClient: Cosmos_Upgrade_V1beta1_MsgClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Upgrade_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the SoftwareUpgrade RPC. This must be called
  /// before calling 'softwareUpgrade'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeSoftwareUpgradeResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade, Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade.path, requestHandler: requestHandler)
  }

  public func enqueueSoftwareUpgradeResponse(
    _ response: Cosmos_Upgrade_V1beta1_MsgSoftwareUpgradeResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Upgrade_V1beta1_MsgSoftwareUpgrade>) -> () = { _ in }
  ) {
    let stream = self.makeSoftwareUpgradeResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'SoftwareUpgrade'
  public var hasSoftwareUpgradeResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.softwareUpgrade.path)
  }

  /// Make a unary response for the CancelUpgrade RPC. This must be called
  /// before calling 'cancelUpgrade'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeCancelUpgradeResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade, Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade.path, requestHandler: requestHandler)
  }

  public func enqueueCancelUpgradeResponse(
    _ response: Cosmos_Upgrade_V1beta1_MsgCancelUpgradeResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Upgrade_V1beta1_MsgCancelUpgrade>) -> () = { _ in }
  ) {
    let stream = self.makeCancelUpgradeResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'CancelUpgrade'
  public var hasCancelUpgradeResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Upgrade_V1beta1_MsgClientMetadata.Methods.cancelUpgrade.path)
  }
}

