//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/distribution/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Msg defines the distribution Msg service.
///
/// Usage: instantiate `Cosmos_Distribution_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Distribution_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func setWithdrawAddress(
    _ request: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse>

  func withdrawDelegatorReward(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse>

  func withdrawValidatorCommission(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse>

  func fundCommunityPool(
    _ request: Cosmos_Distribution_V1beta1_MsgFundCommunityPool,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse>

  func updateParams(
    _ request: Cosmos_Distribution_V1beta1_MsgUpdateParams,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse>

  func communityPoolSpend(
    _ request: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse>

  func depositValidatorRewardsPool(
    _ request: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse>
}

extension Cosmos_Distribution_V1beta1_MsgClientProtocol {
  public var serviceName: String {
    return "cosmos.distribution.v1beta1.Msg"
  }

  /// SetWithdrawAddress defines a method to change the withdraw address
  /// for a delegator (or validator self-delegation).
  ///
  /// - Parameters:
  ///   - request: Request to send to SetWithdrawAddress.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setWithdrawAddress(
    _ request: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetWithdrawAddressInterceptors() ?? []
    )
  }

  /// WithdrawDelegatorReward defines a method to withdraw rewards of delegator
  /// from a single validator.
  ///
  /// - Parameters:
  ///   - request: Request to send to WithdrawDelegatorReward.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func withdrawDelegatorReward(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawDelegatorRewardInterceptors() ?? []
    )
  }

  /// WithdrawValidatorCommission defines a method to withdraw the
  /// full commission to the validator address.
  ///
  /// - Parameters:
  ///   - request: Request to send to WithdrawValidatorCommission.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func withdrawValidatorCommission(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawValidatorCommissionInterceptors() ?? []
    )
  }

  /// FundCommunityPool defines a method to allow an account to directly
  /// fund the community pool.
  ///
  /// - Parameters:
  ///   - request: Request to send to FundCommunityPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func fundCommunityPool(
    _ request: Cosmos_Distribution_V1beta1_MsgFundCommunityPool,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFundCommunityPoolInterceptors() ?? []
    )
  }

  /// UpdateParams defines a governance operation for updating the x/distribution
  /// module parameters. The authority is defined in the keeper.
  ///
  /// Since: cosmos-sdk 0.47
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateParams(
    _ request: Cosmos_Distribution_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }

  /// CommunityPoolSpend defines a governance operation for sending tokens from
  /// the community pool in the x/distribution module to another account, which
  /// could be the governance module itself. The authority is defined in the
  /// keeper.
  ///
  /// Since: cosmos-sdk 0.47
  ///
  /// - Parameters:
  ///   - request: Request to send to CommunityPoolSpend.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func communityPoolSpend(
    _ request: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommunityPoolSpendInterceptors() ?? []
    )
  }

  /// DepositValidatorRewardsPool defines a method to provide additional rewards
  /// to delegators to a specific validator.
  ///
  /// Since: cosmos-sdk 0.48
  ///
  /// - Parameters:
  ///   - request: Request to send to DepositValidatorRewardsPool.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func depositValidatorRewardsPool(
    _ request: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositValidatorRewardsPoolInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Distribution_V1beta1_MsgClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Distribution_V1beta1_MsgNIOClient")
public final class Cosmos_Distribution_V1beta1_MsgClient: Cosmos_Distribution_V1beta1_MsgClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.distribution.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Distribution_V1beta1_MsgNIOClient: Cosmos_Distribution_V1beta1_MsgClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.distribution.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Msg defines the distribution Msg service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Distribution_V1beta1_MsgAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func makeSetWithdrawAddressCall(
    _ request: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse>

  func makeWithdrawDelegatorRewardCall(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse>

  func makeWithdrawValidatorCommissionCall(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse>

  func makeFundCommunityPoolCall(
    _ request: Cosmos_Distribution_V1beta1_MsgFundCommunityPool,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse>

  func makeUpdateParamsCall(
    _ request: Cosmos_Distribution_V1beta1_MsgUpdateParams,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse>

  func makeCommunityPoolSpendCall(
    _ request: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse>

  func makeDepositValidatorRewardsPoolCall(
    _ request: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Distribution_V1beta1_MsgAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Distribution_V1beta1_MsgClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeSetWithdrawAddressCall(
    _ request: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetWithdrawAddressInterceptors() ?? []
    )
  }

  public func makeWithdrawDelegatorRewardCall(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawDelegatorRewardInterceptors() ?? []
    )
  }

  public func makeWithdrawValidatorCommissionCall(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawValidatorCommissionInterceptors() ?? []
    )
  }

  public func makeFundCommunityPoolCall(
    _ request: Cosmos_Distribution_V1beta1_MsgFundCommunityPool,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFundCommunityPoolInterceptors() ?? []
    )
  }

  public func makeUpdateParamsCall(
    _ request: Cosmos_Distribution_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }

  public func makeCommunityPoolSpendCall(
    _ request: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommunityPoolSpendInterceptors() ?? []
    )
  }

  public func makeDepositValidatorRewardsPoolCall(
    _ request: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositValidatorRewardsPoolInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Distribution_V1beta1_MsgAsyncClientProtocol {
  public func setWithdrawAddress(
    _ request: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetWithdrawAddressInterceptors() ?? []
    )
  }

  public func withdrawDelegatorReward(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawDelegatorRewardInterceptors() ?? []
    )
  }

  public func withdrawValidatorCommission(
    _ request: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawValidatorCommissionInterceptors() ?? []
    )
  }

  public func fundCommunityPool(
    _ request: Cosmos_Distribution_V1beta1_MsgFundCommunityPool,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFundCommunityPoolInterceptors() ?? []
    )
  }

  public func updateParams(
    _ request: Cosmos_Distribution_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }

  public func communityPoolSpend(
    _ request: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommunityPoolSpendInterceptors() ?? []
    )
  }

  public func depositValidatorRewardsPool(
    _ request: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositValidatorRewardsPoolInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Distribution_V1beta1_MsgAsyncClient: Cosmos_Distribution_V1beta1_MsgAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'setWithdrawAddress'.
  func makeSetWithdrawAddressInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse>]

  /// - Returns: Interceptors to use when invoking 'withdrawDelegatorReward'.
  func makeWithdrawDelegatorRewardInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse>]

  /// - Returns: Interceptors to use when invoking 'withdrawValidatorCommission'.
  func makeWithdrawValidatorCommissionInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse>]

  /// - Returns: Interceptors to use when invoking 'fundCommunityPool'.
  func makeFundCommunityPoolInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse>]

  /// - Returns: Interceptors to use when invoking 'updateParams'.
  func makeUpdateParamsInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'communityPoolSpend'.
  func makeCommunityPoolSpendInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse>]

  /// - Returns: Interceptors to use when invoking 'depositValidatorRewardsPool'.
  func makeDepositValidatorRewardsPoolInterceptors() -> [ClientInterceptor<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse>]
}

public enum Cosmos_Distribution_V1beta1_MsgClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Msg",
    fullName: "cosmos.distribution.v1beta1.Msg",
    methods: [
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend,
      Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool,
    ]
  )

  public enum Methods {
    public static let setWithdrawAddress = GRPCMethodDescriptor(
      name: "SetWithdrawAddress",
      path: "/cosmos.distribution.v1beta1.Msg/SetWithdrawAddress",
      type: GRPCCallType.unary
    )

    public static let withdrawDelegatorReward = GRPCMethodDescriptor(
      name: "WithdrawDelegatorReward",
      path: "/cosmos.distribution.v1beta1.Msg/WithdrawDelegatorReward",
      type: GRPCCallType.unary
    )

    public static let withdrawValidatorCommission = GRPCMethodDescriptor(
      name: "WithdrawValidatorCommission",
      path: "/cosmos.distribution.v1beta1.Msg/WithdrawValidatorCommission",
      type: GRPCCallType.unary
    )

    public static let fundCommunityPool = GRPCMethodDescriptor(
      name: "FundCommunityPool",
      path: "/cosmos.distribution.v1beta1.Msg/FundCommunityPool",
      type: GRPCCallType.unary
    )

    public static let updateParams = GRPCMethodDescriptor(
      name: "UpdateParams",
      path: "/cosmos.distribution.v1beta1.Msg/UpdateParams",
      type: GRPCCallType.unary
    )

    public static let communityPoolSpend = GRPCMethodDescriptor(
      name: "CommunityPoolSpend",
      path: "/cosmos.distribution.v1beta1.Msg/CommunityPoolSpend",
      type: GRPCCallType.unary
    )

    public static let depositValidatorRewardsPool = GRPCMethodDescriptor(
      name: "DepositValidatorRewardsPool",
      path: "/cosmos.distribution.v1beta1.Msg/DepositValidatorRewardsPool",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Distribution_V1beta1_MsgTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Distribution_V1beta1_MsgTestClient: Cosmos_Distribution_V1beta1_MsgClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Distribution_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the SetWithdrawAddress RPC. This must be called
  /// before calling 'setWithdrawAddress'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeSetWithdrawAddressResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress, Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress.path, requestHandler: requestHandler)
  }

  public func enqueueSetWithdrawAddressResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgSetWithdrawAddressResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgSetWithdrawAddress>) -> () = { _ in }
  ) {
    let stream = self.makeSetWithdrawAddressResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'SetWithdrawAddress'
  public var hasSetWithdrawAddressResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.setWithdrawAddress.path)
  }

  /// Make a unary response for the WithdrawDelegatorReward RPC. This must be called
  /// before calling 'withdrawDelegatorReward'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeWithdrawDelegatorRewardResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward, Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward.path, requestHandler: requestHandler)
  }

  public func enqueueWithdrawDelegatorRewardResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorRewardResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgWithdrawDelegatorReward>) -> () = { _ in }
  ) {
    let stream = self.makeWithdrawDelegatorRewardResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'WithdrawDelegatorReward'
  public var hasWithdrawDelegatorRewardResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawDelegatorReward.path)
  }

  /// Make a unary response for the WithdrawValidatorCommission RPC. This must be called
  /// before calling 'withdrawValidatorCommission'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeWithdrawValidatorCommissionResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission, Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission.path, requestHandler: requestHandler)
  }

  public func enqueueWithdrawValidatorCommissionResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommissionResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgWithdrawValidatorCommission>) -> () = { _ in }
  ) {
    let stream = self.makeWithdrawValidatorCommissionResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'WithdrawValidatorCommission'
  public var hasWithdrawValidatorCommissionResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.withdrawValidatorCommission.path)
  }

  /// Make a unary response for the FundCommunityPool RPC. This must be called
  /// before calling 'fundCommunityPool'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeFundCommunityPoolResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgFundCommunityPool>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgFundCommunityPool, Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool.path, requestHandler: requestHandler)
  }

  public func enqueueFundCommunityPoolResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgFundCommunityPoolResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgFundCommunityPool>) -> () = { _ in }
  ) {
    let stream = self.makeFundCommunityPoolResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'FundCommunityPool'
  public var hasFundCommunityPoolResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.fundCommunityPool.path)
  }

  /// Make a unary response for the UpdateParams RPC. This must be called
  /// before calling 'updateParams'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeUpdateParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgUpdateParams>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgUpdateParams, Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams.path, requestHandler: requestHandler)
  }

  public func enqueueUpdateParamsResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgUpdateParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgUpdateParams>) -> () = { _ in }
  ) {
    let stream = self.makeUpdateParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'UpdateParams'
  public var hasUpdateParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.updateParams.path)
  }

  /// Make a unary response for the CommunityPoolSpend RPC. This must be called
  /// before calling 'communityPoolSpend'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeCommunityPoolSpendResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend, Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend.path, requestHandler: requestHandler)
  }

  public func enqueueCommunityPoolSpendResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgCommunityPoolSpendResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgCommunityPoolSpend>) -> () = { _ in }
  ) {
    let stream = self.makeCommunityPoolSpendResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'CommunityPoolSpend'
  public var hasCommunityPoolSpendResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.communityPoolSpend.path)
  }

  /// Make a unary response for the DepositValidatorRewardsPool RPC. This must be called
  /// before calling 'depositValidatorRewardsPool'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeDepositValidatorRewardsPoolResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool, Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool.path, requestHandler: requestHandler)
  }

  public func enqueueDepositValidatorRewardsPoolResponse(
    _ response: Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPoolResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Distribution_V1beta1_MsgDepositValidatorRewardsPool>) -> () = { _ in }
  ) {
    let stream = self.makeDepositValidatorRewardsPoolResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'DepositValidatorRewardsPool'
  public var hasDepositValidatorRewardsPoolResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Distribution_V1beta1_MsgClientMetadata.Methods.depositValidatorRewardsPool.path)
  }
}

