//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/slashing/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query provides defines the gRPC querier service
///
/// Usage: instantiate `Cosmos_Slashing_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Slashing_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func params(
    _ request: Cosmos_Slashing_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse>

  func signingInfo(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse>

  func signingInfos(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfosRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse>
}

extension Cosmos_Slashing_V1beta1_QueryClientProtocol {
  public var serviceName: String {
    return "cosmos.slashing.v1beta1.Query"
  }

  /// Params queries the parameters of slashing module
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func params(
    _ request: Cosmos_Slashing_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// SigningInfo queries the signing info of given cons address
  ///
  /// - Parameters:
  ///   - request: Request to send to SigningInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func signingInfo(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfoInterceptors() ?? []
    )
  }

  /// SigningInfos queries signing info of all validators
  ///
  /// - Parameters:
  ///   - request: Request to send to SigningInfos.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func signingInfos(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfosRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfosInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Slashing_V1beta1_QueryClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Slashing_V1beta1_QueryNIOClient")
public final class Cosmos_Slashing_V1beta1_QueryClient: Cosmos_Slashing_V1beta1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.slashing.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Slashing_V1beta1_QueryNIOClient: Cosmos_Slashing_V1beta1_QueryClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.slashing.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Query provides defines the gRPC querier service
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Slashing_V1beta1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func makeParamsCall(
    _ request: Cosmos_Slashing_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse>

  func makeSigningInfoCall(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse>

  func makeSigningInfosCall(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfosRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Slashing_V1beta1_QueryAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Slashing_V1beta1_QueryClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeParamsCall(
    _ request: Cosmos_Slashing_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func makeSigningInfoCall(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfoInterceptors() ?? []
    )
  }

  public func makeSigningInfosCall(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfosRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfosInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Slashing_V1beta1_QueryAsyncClientProtocol {
  public func params(
    _ request: Cosmos_Slashing_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Slashing_V1beta1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func signingInfo(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Slashing_V1beta1_QuerySigningInfoResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfoInterceptors() ?? []
    )
  }

  public func signingInfos(
    _ request: Cosmos_Slashing_V1beta1_QuerySigningInfosRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Slashing_V1beta1_QuerySigningInfosResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSigningInfosInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Slashing_V1beta1_QueryAsyncClient: Cosmos_Slashing_V1beta1_QueryAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'signingInfo'.
  func makeSigningInfoInterceptors() -> [ClientInterceptor<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse>]

  /// - Returns: Interceptors to use when invoking 'signingInfos'.
  func makeSigningInfosInterceptors() -> [ClientInterceptor<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse>]
}

public enum Cosmos_Slashing_V1beta1_QueryClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "cosmos.slashing.v1beta1.Query",
    methods: [
      Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params,
      Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo,
      Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos,
    ]
  )

  public enum Methods {
    public static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/cosmos.slashing.v1beta1.Query/Params",
      type: GRPCCallType.unary
    )

    public static let signingInfo = GRPCMethodDescriptor(
      name: "SigningInfo",
      path: "/cosmos.slashing.v1beta1.Query/SigningInfo",
      type: GRPCCallType.unary
    )

    public static let signingInfos = GRPCMethodDescriptor(
      name: "SigningInfos",
      path: "/cosmos.slashing.v1beta1.Query/SigningInfos",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Slashing_V1beta1_QueryTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Slashing_V1beta1_QueryTestClient: Cosmos_Slashing_V1beta1_QueryClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the Params RPC. This must be called
  /// before calling 'params'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QueryParamsRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Slashing_V1beta1_QueryParamsRequest, Cosmos_Slashing_V1beta1_QueryParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params.path, requestHandler: requestHandler)
  }

  public func enqueueParamsResponse(
    _ response: Cosmos_Slashing_V1beta1_QueryParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QueryParamsRequest>) -> () = { _ in }
  ) {
    let stream = self.makeParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Params'
  public var hasParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.params.path)
  }

  /// Make a unary response for the SigningInfo RPC. This must be called
  /// before calling 'signingInfo'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeSigningInfoResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest, Cosmos_Slashing_V1beta1_QuerySigningInfoResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo.path, requestHandler: requestHandler)
  }

  public func enqueueSigningInfoResponse(
    _ response: Cosmos_Slashing_V1beta1_QuerySigningInfoResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QuerySigningInfoRequest>) -> () = { _ in }
  ) {
    let stream = self.makeSigningInfoResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'SigningInfo'
  public var hasSigningInfoResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfo.path)
  }

  /// Make a unary response for the SigningInfos RPC. This must be called
  /// before calling 'signingInfos'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeSigningInfosResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest, Cosmos_Slashing_V1beta1_QuerySigningInfosResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos.path, requestHandler: requestHandler)
  }

  public func enqueueSigningInfosResponse(
    _ response: Cosmos_Slashing_V1beta1_QuerySigningInfosResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_QuerySigningInfosRequest>) -> () = { _ in }
  ) {
    let stream = self.makeSigningInfosResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'SigningInfos'
  public var hasSigningInfosResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Slashing_V1beta1_QueryClientMetadata.Methods.signingInfos.path)
  }
}

