//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/authz/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Msg defines the authz Msg service.
///
/// Usage: instantiate `Cosmos_Authz_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Authz_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func grant(
    _ request: Cosmos_Authz_V1beta1_MsgGrant,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse>

  func exec(
    _ request: Cosmos_Authz_V1beta1_MsgExec,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse>

  func revoke(
    _ request: Cosmos_Authz_V1beta1_MsgRevoke,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse>
}

extension Cosmos_Authz_V1beta1_MsgClientProtocol {
  public var serviceName: String {
    return "cosmos.authz.v1beta1.Msg"
  }

  /// Grant grants the provided authorization to the grantee on the granter's
  /// account with the provided expiration time. If there is already a grant
  /// for the given (granter, grantee, Authorization) triple, then the grant
  /// will be overwritten.
  ///
  /// - Parameters:
  ///   - request: Request to send to Grant.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func grant(
    _ request: Cosmos_Authz_V1beta1_MsgGrant,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGrantInterceptors() ?? []
    )
  }

  /// Exec attempts to execute the provided messages using
  /// authorizations granted to the grantee. Each message should have only
  /// one signer corresponding to the granter of the authorization.
  ///
  /// - Parameters:
  ///   - request: Request to send to Exec.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func exec(
    _ request: Cosmos_Authz_V1beta1_MsgExec,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecInterceptors() ?? []
    )
  }

  /// Revoke revokes any authorization corresponding to the provided method name on the
  /// granter's account that has been granted to the grantee.
  ///
  /// - Parameters:
  ///   - request: Request to send to Revoke.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func revoke(
    _ request: Cosmos_Authz_V1beta1_MsgRevoke,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevokeInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Authz_V1beta1_MsgClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Authz_V1beta1_MsgNIOClient")
public final class Cosmos_Authz_V1beta1_MsgClient: Cosmos_Authz_V1beta1_MsgClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.authz.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Authz_V1beta1_MsgNIOClient: Cosmos_Authz_V1beta1_MsgClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.authz.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Msg defines the authz Msg service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Authz_V1beta1_MsgAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func makeGrantCall(
    _ request: Cosmos_Authz_V1beta1_MsgGrant,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse>

  func makeExecCall(
    _ request: Cosmos_Authz_V1beta1_MsgExec,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse>

  func makeRevokeCall(
    _ request: Cosmos_Authz_V1beta1_MsgRevoke,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Authz_V1beta1_MsgAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Authz_V1beta1_MsgClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGrantCall(
    _ request: Cosmos_Authz_V1beta1_MsgGrant,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGrantInterceptors() ?? []
    )
  }

  public func makeExecCall(
    _ request: Cosmos_Authz_V1beta1_MsgExec,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecInterceptors() ?? []
    )
  }

  public func makeRevokeCall(
    _ request: Cosmos_Authz_V1beta1_MsgRevoke,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevokeInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Authz_V1beta1_MsgAsyncClientProtocol {
  public func grant(
    _ request: Cosmos_Authz_V1beta1_MsgGrant,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Authz_V1beta1_MsgGrantResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGrantInterceptors() ?? []
    )
  }

  public func exec(
    _ request: Cosmos_Authz_V1beta1_MsgExec,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Authz_V1beta1_MsgExecResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExecInterceptors() ?? []
    )
  }

  public func revoke(
    _ request: Cosmos_Authz_V1beta1_MsgRevoke,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Authz_V1beta1_MsgRevokeResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevokeInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Authz_V1beta1_MsgAsyncClient: Cosmos_Authz_V1beta1_MsgAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'grant'.
  func makeGrantInterceptors() -> [ClientInterceptor<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse>]

  /// - Returns: Interceptors to use when invoking 'exec'.
  func makeExecInterceptors() -> [ClientInterceptor<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse>]

  /// - Returns: Interceptors to use when invoking 'revoke'.
  func makeRevokeInterceptors() -> [ClientInterceptor<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse>]
}

public enum Cosmos_Authz_V1beta1_MsgClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Msg",
    fullName: "cosmos.authz.v1beta1.Msg",
    methods: [
      Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant,
      Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec,
      Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke,
    ]
  )

  public enum Methods {
    public static let grant = GRPCMethodDescriptor(
      name: "Grant",
      path: "/cosmos.authz.v1beta1.Msg/Grant",
      type: GRPCCallType.unary
    )

    public static let exec = GRPCMethodDescriptor(
      name: "Exec",
      path: "/cosmos.authz.v1beta1.Msg/Exec",
      type: GRPCCallType.unary
    )

    public static let revoke = GRPCMethodDescriptor(
      name: "Revoke",
      path: "/cosmos.authz.v1beta1.Msg/Revoke",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Authz_V1beta1_MsgTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Authz_V1beta1_MsgTestClient: Cosmos_Authz_V1beta1_MsgClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Authz_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the Grant RPC. This must be called
  /// before calling 'grant'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeGrantResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgGrant>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Authz_V1beta1_MsgGrant, Cosmos_Authz_V1beta1_MsgGrantResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant.path, requestHandler: requestHandler)
  }

  public func enqueueGrantResponse(
    _ response: Cosmos_Authz_V1beta1_MsgGrantResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgGrant>) -> () = { _ in }
  ) {
    let stream = self.makeGrantResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Grant'
  public var hasGrantResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.grant.path)
  }

  /// Make a unary response for the Exec RPC. This must be called
  /// before calling 'exec'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeExecResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgExec>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Authz_V1beta1_MsgExec, Cosmos_Authz_V1beta1_MsgExecResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec.path, requestHandler: requestHandler)
  }

  public func enqueueExecResponse(
    _ response: Cosmos_Authz_V1beta1_MsgExecResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgExec>) -> () = { _ in }
  ) {
    let stream = self.makeExecResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Exec'
  public var hasExecResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.exec.path)
  }

  /// Make a unary response for the Revoke RPC. This must be called
  /// before calling 'revoke'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeRevokeResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgRevoke>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Authz_V1beta1_MsgRevoke, Cosmos_Authz_V1beta1_MsgRevokeResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke.path, requestHandler: requestHandler)
  }

  public func enqueueRevokeResponse(
    _ response: Cosmos_Authz_V1beta1_MsgRevokeResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Authz_V1beta1_MsgRevoke>) -> () = { _ in }
  ) {
    let stream = self.makeRevokeResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Revoke'
  public var hasRevokeResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Authz_V1beta1_MsgClientMetadata.Methods.revoke.path)
  }
}

