//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/params/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Cosmos_Params_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Params_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func params(
    _ request: Cosmos_Params_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse>

  func subspaces(
    _ request: Cosmos_Params_V1beta1_QuerySubspacesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse>
}

extension Cosmos_Params_V1beta1_QueryClientProtocol {
  public var serviceName: String {
    return "cosmos.params.v1beta1.Query"
  }

  /// Params queries a specific parameter of a module, given its subspace and
  /// key.
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func params(
    _ request: Cosmos_Params_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// Subspaces queries for all registered subspaces and all keys for a subspace.
  ///
  /// Since: cosmos-sdk 0.46
  ///
  /// - Parameters:
  ///   - request: Request to send to Subspaces.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func subspaces(
    _ request: Cosmos_Params_V1beta1_QuerySubspacesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubspacesInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Params_V1beta1_QueryClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Params_V1beta1_QueryNIOClient")
public final class Cosmos_Params_V1beta1_QueryClient: Cosmos_Params_V1beta1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.params.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Params_V1beta1_QueryNIOClient: Cosmos_Params_V1beta1_QueryClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.params.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Params_V1beta1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func makeParamsCall(
    _ request: Cosmos_Params_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse>

  func makeSubspacesCall(
    _ request: Cosmos_Params_V1beta1_QuerySubspacesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Params_V1beta1_QueryAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Params_V1beta1_QueryClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeParamsCall(
    _ request: Cosmos_Params_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func makeSubspacesCall(
    _ request: Cosmos_Params_V1beta1_QuerySubspacesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubspacesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Params_V1beta1_QueryAsyncClientProtocol {
  public func params(
    _ request: Cosmos_Params_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Params_V1beta1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func subspaces(
    _ request: Cosmos_Params_V1beta1_QuerySubspacesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Params_V1beta1_QuerySubspacesResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSubspacesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Params_V1beta1_QueryAsyncClient: Cosmos_Params_V1beta1_QueryAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'subspaces'.
  func makeSubspacesInterceptors() -> [ClientInterceptor<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse>]
}

public enum Cosmos_Params_V1beta1_QueryClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "cosmos.params.v1beta1.Query",
    methods: [
      Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params,
      Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces,
    ]
  )

  public enum Methods {
    public static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/cosmos.params.v1beta1.Query/Params",
      type: GRPCCallType.unary
    )

    public static let subspaces = GRPCMethodDescriptor(
      name: "Subspaces",
      path: "/cosmos.params.v1beta1.Query/Subspaces",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Params_V1beta1_QueryTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Params_V1beta1_QueryTestClient: Cosmos_Params_V1beta1_QueryClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Params_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the Params RPC. This must be called
  /// before calling 'params'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Params_V1beta1_QueryParamsRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Params_V1beta1_QueryParamsRequest, Cosmos_Params_V1beta1_QueryParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params.path, requestHandler: requestHandler)
  }

  public func enqueueParamsResponse(
    _ response: Cosmos_Params_V1beta1_QueryParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Params_V1beta1_QueryParamsRequest>) -> () = { _ in }
  ) {
    let stream = self.makeParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Params'
  public var hasParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.params.path)
  }

  /// Make a unary response for the Subspaces RPC. This must be called
  /// before calling 'subspaces'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeSubspacesResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Params_V1beta1_QuerySubspacesRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Params_V1beta1_QuerySubspacesRequest, Cosmos_Params_V1beta1_QuerySubspacesResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces.path, requestHandler: requestHandler)
  }

  public func enqueueSubspacesResponse(
    _ response: Cosmos_Params_V1beta1_QuerySubspacesResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Params_V1beta1_QuerySubspacesRequest>) -> () = { _ in }
  ) {
    let stream = self.makeSubspacesResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Subspaces'
  public var hasSubspacesResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Params_V1beta1_QueryClientMetadata.Methods.subspaces.path)
  }
}

