//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: evmos/revenue/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Evmos_Revenue_V1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Evmos_Revenue_V1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? { get }

  func revenues(
    _ request: Evmos_Revenue_V1_QueryRevenuesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse>

  func revenue(
    _ request: Evmos_Revenue_V1_QueryRevenueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse>

  func params(
    _ request: Evmos_Revenue_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse>

  func deployerRevenues(
    _ request: Evmos_Revenue_V1_QueryDeployerRevenuesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse>

  func withdrawerRevenues(
    _ request: Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse>
}

extension Evmos_Revenue_V1_QueryClientProtocol {
  public var serviceName: String {
    return "evmos.revenue.v1.Query"
  }

  /// Revenues retrieves all registered revenues
  ///
  /// - Parameters:
  ///   - request: Request to send to Revenues.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func revenues(
    _ request: Evmos_Revenue_V1_QueryRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse> {
    return self.makeUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenuesInterceptors() ?? []
    )
  }

  /// Revenue retrieves a registered revenue for a given contract address
  ///
  /// - Parameters:
  ///   - request: Request to send to Revenue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func revenue(
    _ request: Evmos_Revenue_V1_QueryRevenueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse> {
    return self.makeUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenueInterceptors() ?? []
    )
  }

  /// Params retrieves the revenue module params
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func params(
    _ request: Evmos_Revenue_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// DeployerRevenues retrieves all revenues that a given deployer has
  /// registered
  ///
  /// - Parameters:
  ///   - request: Request to send to DeployerRevenues.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deployerRevenues(
    _ request: Evmos_Revenue_V1_QueryDeployerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse> {
    return self.makeUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeployerRevenuesInterceptors() ?? []
    )
  }

  /// WithdrawerRevenues retrieves all revenues with a given withdrawer
  /// address
  ///
  /// - Parameters:
  ///   - request: Request to send to WithdrawerRevenues.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func withdrawerRevenues(
    _ request: Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse> {
    return self.makeUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawerRevenuesInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Evmos_Revenue_V1_QueryClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Evmos_Revenue_V1_QueryNIOClient")
public final class Evmos_Revenue_V1_QueryClient: Evmos_Revenue_V1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the evmos.revenue.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Evmos_Revenue_V1_QueryNIOClient: Evmos_Revenue_V1_QueryClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the evmos.revenue.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Evmos_Revenue_V1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? { get }

  func makeRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryRevenuesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse>

  func makeRevenueCall(
    _ request: Evmos_Revenue_V1_QueryRevenueRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse>

  func makeParamsCall(
    _ request: Evmos_Revenue_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse>

  func makeDeployerRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryDeployerRevenuesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse>

  func makeWithdrawerRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Revenue_V1_QueryAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Evmos_Revenue_V1_QueryClientMetadata.serviceDescriptor
  }

  public var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenuesInterceptors() ?? []
    )
  }

  public func makeRevenueCall(
    _ request: Evmos_Revenue_V1_QueryRevenueRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenueInterceptors() ?? []
    )
  }

  public func makeParamsCall(
    _ request: Evmos_Revenue_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func makeDeployerRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryDeployerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeployerRevenuesInterceptors() ?? []
    )
  }

  public func makeWithdrawerRevenuesCall(
    _ request: Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawerRevenuesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Revenue_V1_QueryAsyncClientProtocol {
  public func revenues(
    _ request: Evmos_Revenue_V1_QueryRevenuesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Revenue_V1_QueryRevenuesResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenuesInterceptors() ?? []
    )
  }

  public func revenue(
    _ request: Evmos_Revenue_V1_QueryRevenueRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Revenue_V1_QueryRevenueResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevenueInterceptors() ?? []
    )
  }

  public func params(
    _ request: Evmos_Revenue_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Revenue_V1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func deployerRevenues(
    _ request: Evmos_Revenue_V1_QueryDeployerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Revenue_V1_QueryDeployerRevenuesResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeployerRevenuesInterceptors() ?? []
    )
  }

  public func withdrawerRevenues(
    _ request: Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWithdrawerRevenuesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Evmos_Revenue_V1_QueryAsyncClient: Evmos_Revenue_V1_QueryAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'revenues'.
  func makeRevenuesInterceptors() -> [ClientInterceptor<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse>]

  /// - Returns: Interceptors to use when invoking 'revenue'.
  func makeRevenueInterceptors() -> [ClientInterceptor<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse>]

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'deployerRevenues'.
  func makeDeployerRevenuesInterceptors() -> [ClientInterceptor<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse>]

  /// - Returns: Interceptors to use when invoking 'withdrawerRevenues'.
  func makeWithdrawerRevenuesInterceptors() -> [ClientInterceptor<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse>]
}

public enum Evmos_Revenue_V1_QueryClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "evmos.revenue.v1.Query",
    methods: [
      Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues,
      Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue,
      Evmos_Revenue_V1_QueryClientMetadata.Methods.params,
      Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues,
      Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues,
    ]
  )

  public enum Methods {
    public static let revenues = GRPCMethodDescriptor(
      name: "Revenues",
      path: "/evmos.revenue.v1.Query/Revenues",
      type: GRPCCallType.unary
    )

    public static let revenue = GRPCMethodDescriptor(
      name: "Revenue",
      path: "/evmos.revenue.v1.Query/Revenue",
      type: GRPCCallType.unary
    )

    public static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/evmos.revenue.v1.Query/Params",
      type: GRPCCallType.unary
    )

    public static let deployerRevenues = GRPCMethodDescriptor(
      name: "DeployerRevenues",
      path: "/evmos.revenue.v1.Query/DeployerRevenues",
      type: GRPCCallType.unary
    )

    public static let withdrawerRevenues = GRPCMethodDescriptor(
      name: "WithdrawerRevenues",
      path: "/evmos.revenue.v1.Query/WithdrawerRevenues",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Evmos_Revenue_V1_QueryTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Evmos_Revenue_V1_QueryTestClient: Evmos_Revenue_V1_QueryClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Revenue_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the Revenues RPC. This must be called
  /// before calling 'revenues'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeRevenuesResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryRevenuesRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Revenue_V1_QueryRevenuesRequest, Evmos_Revenue_V1_QueryRevenuesResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues.path, requestHandler: requestHandler)
  }

  public func enqueueRevenuesResponse(
    _ response: Evmos_Revenue_V1_QueryRevenuesResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryRevenuesRequest>) -> () = { _ in }
  ) {
    let stream = self.makeRevenuesResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Revenues'
  public var hasRevenuesResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenues.path)
  }

  /// Make a unary response for the Revenue RPC. This must be called
  /// before calling 'revenue'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeRevenueResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryRevenueRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Revenue_V1_QueryRevenueRequest, Evmos_Revenue_V1_QueryRevenueResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue.path, requestHandler: requestHandler)
  }

  public func enqueueRevenueResponse(
    _ response: Evmos_Revenue_V1_QueryRevenueResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryRevenueRequest>) -> () = { _ in }
  ) {
    let stream = self.makeRevenueResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Revenue'
  public var hasRevenueResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Revenue_V1_QueryClientMetadata.Methods.revenue.path)
  }

  /// Make a unary response for the Params RPC. This must be called
  /// before calling 'params'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryParamsRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Revenue_V1_QueryParamsRequest, Evmos_Revenue_V1_QueryParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Revenue_V1_QueryClientMetadata.Methods.params.path, requestHandler: requestHandler)
  }

  public func enqueueParamsResponse(
    _ response: Evmos_Revenue_V1_QueryParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryParamsRequest>) -> () = { _ in }
  ) {
    let stream = self.makeParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Params'
  public var hasParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Revenue_V1_QueryClientMetadata.Methods.params.path)
  }

  /// Make a unary response for the DeployerRevenues RPC. This must be called
  /// before calling 'deployerRevenues'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeDeployerRevenuesResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryDeployerRevenuesRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Revenue_V1_QueryDeployerRevenuesRequest, Evmos_Revenue_V1_QueryDeployerRevenuesResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues.path, requestHandler: requestHandler)
  }

  public func enqueueDeployerRevenuesResponse(
    _ response: Evmos_Revenue_V1_QueryDeployerRevenuesResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryDeployerRevenuesRequest>) -> () = { _ in }
  ) {
    let stream = self.makeDeployerRevenuesResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'DeployerRevenues'
  public var hasDeployerRevenuesResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Revenue_V1_QueryClientMetadata.Methods.deployerRevenues.path)
  }

  /// Make a unary response for the WithdrawerRevenues RPC. This must be called
  /// before calling 'withdrawerRevenues'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeWithdrawerRevenuesResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest, Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues.path, requestHandler: requestHandler)
  }

  public func enqueueWithdrawerRevenuesResponse(
    _ response: Evmos_Revenue_V1_QueryWithdrawerRevenuesResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Revenue_V1_QueryWithdrawerRevenuesRequest>) -> () = { _ in }
  ) {
    let stream = self.makeWithdrawerRevenuesResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'WithdrawerRevenues'
  public var hasWithdrawerRevenuesResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Revenue_V1_QueryClientMetadata.Methods.withdrawerRevenues.path)
  }
}

