//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: evmos/claims/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Evmos_Claims_V1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Evmos_Claims_V1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? { get }

  func totalUnclaimed(
    _ request: Evmos_Claims_V1_QueryTotalUnclaimedRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse>

  func params(
    _ request: Evmos_Claims_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse>

  func claimsRecords(
    _ request: Evmos_Claims_V1_QueryClaimsRecordsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse>

  func claimsRecord(
    _ request: Evmos_Claims_V1_QueryClaimsRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse>
}

extension Evmos_Claims_V1_QueryClientProtocol {
  public var serviceName: String {
    return "evmos.claims.v1.Query"
  }

  /// TotalUnclaimed queries the total unclaimed tokens from the airdrop
  ///
  /// - Parameters:
  ///   - request: Request to send to TotalUnclaimed.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func totalUnclaimed(
    _ request: Evmos_Claims_V1_QueryTotalUnclaimedRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse> {
    return self.makeUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTotalUnclaimedInterceptors() ?? []
    )
  }

  /// Params returns the claims module parameters
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func params(
    _ request: Evmos_Claims_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// ClaimsRecords returns all claims records
  ///
  /// - Parameters:
  ///   - request: Request to send to ClaimsRecords.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func claimsRecords(
    _ request: Evmos_Claims_V1_QueryClaimsRecordsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse> {
    return self.makeUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordsInterceptors() ?? []
    )
  }

  /// ClaimsRecord returns the claims record for a given address
  ///
  /// - Parameters:
  ///   - request: Request to send to ClaimsRecord.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func claimsRecord(
    _ request: Evmos_Claims_V1_QueryClaimsRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse> {
    return self.makeUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Evmos_Claims_V1_QueryClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Evmos_Claims_V1_QueryNIOClient")
public final class Evmos_Claims_V1_QueryClient: Evmos_Claims_V1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the evmos.claims.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Evmos_Claims_V1_QueryNIOClient: Evmos_Claims_V1_QueryClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the evmos.claims.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Evmos_Claims_V1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? { get }

  func makeTotalUnclaimedCall(
    _ request: Evmos_Claims_V1_QueryTotalUnclaimedRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse>

  func makeParamsCall(
    _ request: Evmos_Claims_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse>

  func makeClaimsRecordsCall(
    _ request: Evmos_Claims_V1_QueryClaimsRecordsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse>

  func makeClaimsRecordCall(
    _ request: Evmos_Claims_V1_QueryClaimsRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Claims_V1_QueryAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Evmos_Claims_V1_QueryClientMetadata.serviceDescriptor
  }

  public var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeTotalUnclaimedCall(
    _ request: Evmos_Claims_V1_QueryTotalUnclaimedRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTotalUnclaimedInterceptors() ?? []
    )
  }

  public func makeParamsCall(
    _ request: Evmos_Claims_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func makeClaimsRecordsCall(
    _ request: Evmos_Claims_V1_QueryClaimsRecordsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordsInterceptors() ?? []
    )
  }

  public func makeClaimsRecordCall(
    _ request: Evmos_Claims_V1_QueryClaimsRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Claims_V1_QueryAsyncClientProtocol {
  public func totalUnclaimed(
    _ request: Evmos_Claims_V1_QueryTotalUnclaimedRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Claims_V1_QueryTotalUnclaimedResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTotalUnclaimedInterceptors() ?? []
    )
  }

  public func params(
    _ request: Evmos_Claims_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Claims_V1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  public func claimsRecords(
    _ request: Evmos_Claims_V1_QueryClaimsRecordsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Claims_V1_QueryClaimsRecordsResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordsInterceptors() ?? []
    )
  }

  public func claimsRecord(
    _ request: Evmos_Claims_V1_QueryClaimsRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Claims_V1_QueryClaimsRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeClaimsRecordInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Evmos_Claims_V1_QueryAsyncClient: Evmos_Claims_V1_QueryAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'totalUnclaimed'.
  func makeTotalUnclaimedInterceptors() -> [ClientInterceptor<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse>]

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'claimsRecords'.
  func makeClaimsRecordsInterceptors() -> [ClientInterceptor<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse>]

  /// - Returns: Interceptors to use when invoking 'claimsRecord'.
  func makeClaimsRecordInterceptors() -> [ClientInterceptor<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse>]
}

public enum Evmos_Claims_V1_QueryClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "evmos.claims.v1.Query",
    methods: [
      Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed,
      Evmos_Claims_V1_QueryClientMetadata.Methods.params,
      Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords,
      Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord,
    ]
  )

  public enum Methods {
    public static let totalUnclaimed = GRPCMethodDescriptor(
      name: "TotalUnclaimed",
      path: "/evmos.claims.v1.Query/TotalUnclaimed",
      type: GRPCCallType.unary
    )

    public static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/evmos.claims.v1.Query/Params",
      type: GRPCCallType.unary
    )

    public static let claimsRecords = GRPCMethodDescriptor(
      name: "ClaimsRecords",
      path: "/evmos.claims.v1.Query/ClaimsRecords",
      type: GRPCCallType.unary
    )

    public static let claimsRecord = GRPCMethodDescriptor(
      name: "ClaimsRecord",
      path: "/evmos.claims.v1.Query/ClaimsRecord",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Evmos_Claims_V1_QueryTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Evmos_Claims_V1_QueryTestClient: Evmos_Claims_V1_QueryClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Claims_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the TotalUnclaimed RPC. This must be called
  /// before calling 'totalUnclaimed'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeTotalUnclaimedResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryTotalUnclaimedRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Claims_V1_QueryTotalUnclaimedRequest, Evmos_Claims_V1_QueryTotalUnclaimedResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed.path, requestHandler: requestHandler)
  }

  public func enqueueTotalUnclaimedResponse(
    _ response: Evmos_Claims_V1_QueryTotalUnclaimedResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryTotalUnclaimedRequest>) -> () = { _ in }
  ) {
    let stream = self.makeTotalUnclaimedResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'TotalUnclaimed'
  public var hasTotalUnclaimedResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Claims_V1_QueryClientMetadata.Methods.totalUnclaimed.path)
  }

  /// Make a unary response for the Params RPC. This must be called
  /// before calling 'params'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryParamsRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Claims_V1_QueryParamsRequest, Evmos_Claims_V1_QueryParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Claims_V1_QueryClientMetadata.Methods.params.path, requestHandler: requestHandler)
  }

  public func enqueueParamsResponse(
    _ response: Evmos_Claims_V1_QueryParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryParamsRequest>) -> () = { _ in }
  ) {
    let stream = self.makeParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Params'
  public var hasParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Claims_V1_QueryClientMetadata.Methods.params.path)
  }

  /// Make a unary response for the ClaimsRecords RPC. This must be called
  /// before calling 'claimsRecords'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeClaimsRecordsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryClaimsRecordsRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Claims_V1_QueryClaimsRecordsRequest, Evmos_Claims_V1_QueryClaimsRecordsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords.path, requestHandler: requestHandler)
  }

  public func enqueueClaimsRecordsResponse(
    _ response: Evmos_Claims_V1_QueryClaimsRecordsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryClaimsRecordsRequest>) -> () = { _ in }
  ) {
    let stream = self.makeClaimsRecordsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'ClaimsRecords'
  public var hasClaimsRecordsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecords.path)
  }

  /// Make a unary response for the ClaimsRecord RPC. This must be called
  /// before calling 'claimsRecord'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeClaimsRecordResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryClaimsRecordRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Claims_V1_QueryClaimsRecordRequest, Evmos_Claims_V1_QueryClaimsRecordResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord.path, requestHandler: requestHandler)
  }

  public func enqueueClaimsRecordResponse(
    _ response: Evmos_Claims_V1_QueryClaimsRecordResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Claims_V1_QueryClaimsRecordRequest>) -> () = { _ in }
  ) {
    let stream = self.makeClaimsRecordResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'ClaimsRecord'
  public var hasClaimsRecordResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Claims_V1_QueryClientMetadata.Methods.claimsRecord.path)
  }
}

