//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: evmos/epochs/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Evmos_Epochs_V1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Evmos_Epochs_V1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? { get }

  func epochInfos(
    _ request: Evmos_Epochs_V1_QueryEpochsInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse>

  func currentEpoch(
    _ request: Evmos_Epochs_V1_QueryCurrentEpochRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse>
}

extension Evmos_Epochs_V1_QueryClientProtocol {
  public var serviceName: String {
    return "evmos.epochs.v1.Query"
  }

  /// EpochInfos provide running epochInfos
  ///
  /// - Parameters:
  ///   - request: Request to send to EpochInfos.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func epochInfos(
    _ request: Evmos_Epochs_V1_QueryEpochsInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse> {
    return self.makeUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochInfosInterceptors() ?? []
    )
  }

  /// CurrentEpoch provide current epoch of specified identifier
  ///
  /// - Parameters:
  ///   - request: Request to send to CurrentEpoch.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func currentEpoch(
    _ request: Evmos_Epochs_V1_QueryCurrentEpochRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse> {
    return self.makeUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCurrentEpochInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Evmos_Epochs_V1_QueryClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Evmos_Epochs_V1_QueryNIOClient")
public final class Evmos_Epochs_V1_QueryClient: Evmos_Epochs_V1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the evmos.epochs.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Evmos_Epochs_V1_QueryNIOClient: Evmos_Epochs_V1_QueryClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the evmos.epochs.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Evmos_Epochs_V1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? { get }

  func makeEpochInfosCall(
    _ request: Evmos_Epochs_V1_QueryEpochsInfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse>

  func makeCurrentEpochCall(
    _ request: Evmos_Epochs_V1_QueryCurrentEpochRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Epochs_V1_QueryAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Evmos_Epochs_V1_QueryClientMetadata.serviceDescriptor
  }

  public var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeEpochInfosCall(
    _ request: Evmos_Epochs_V1_QueryEpochsInfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochInfosInterceptors() ?? []
    )
  }

  public func makeCurrentEpochCall(
    _ request: Evmos_Epochs_V1_QueryCurrentEpochRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse> {
    return self.makeAsyncUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCurrentEpochInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Evmos_Epochs_V1_QueryAsyncClientProtocol {
  public func epochInfos(
    _ request: Evmos_Epochs_V1_QueryEpochsInfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Epochs_V1_QueryEpochsInfoResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochInfosInterceptors() ?? []
    )
  }

  public func currentEpoch(
    _ request: Evmos_Epochs_V1_QueryCurrentEpochRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Evmos_Epochs_V1_QueryCurrentEpochResponse {
    return try await self.performAsyncUnaryCall(
      path: Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCurrentEpochInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Evmos_Epochs_V1_QueryAsyncClient: Evmos_Epochs_V1_QueryAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'epochInfos'.
  func makeEpochInfosInterceptors() -> [ClientInterceptor<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse>]

  /// - Returns: Interceptors to use when invoking 'currentEpoch'.
  func makeCurrentEpochInterceptors() -> [ClientInterceptor<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse>]
}

public enum Evmos_Epochs_V1_QueryClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "evmos.epochs.v1.Query",
    methods: [
      Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos,
      Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch,
    ]
  )

  public enum Methods {
    public static let epochInfos = GRPCMethodDescriptor(
      name: "EpochInfos",
      path: "/evmos.epochs.v1.Query/EpochInfos",
      type: GRPCCallType.unary
    )

    public static let currentEpoch = GRPCMethodDescriptor(
      name: "CurrentEpoch",
      path: "/evmos.epochs.v1.Query/CurrentEpoch",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Evmos_Epochs_V1_QueryTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Evmos_Epochs_V1_QueryTestClient: Evmos_Epochs_V1_QueryClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Evmos_Epochs_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the EpochInfos RPC. This must be called
  /// before calling 'epochInfos'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeEpochInfosResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Epochs_V1_QueryEpochsInfoRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Epochs_V1_QueryEpochsInfoRequest, Evmos_Epochs_V1_QueryEpochsInfoResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos.path, requestHandler: requestHandler)
  }

  public func enqueueEpochInfosResponse(
    _ response: Evmos_Epochs_V1_QueryEpochsInfoResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Epochs_V1_QueryEpochsInfoRequest>) -> () = { _ in }
  ) {
    let stream = self.makeEpochInfosResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'EpochInfos'
  public var hasEpochInfosResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Epochs_V1_QueryClientMetadata.Methods.epochInfos.path)
  }

  /// Make a unary response for the CurrentEpoch RPC. This must be called
  /// before calling 'currentEpoch'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeCurrentEpochResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Epochs_V1_QueryCurrentEpochRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Evmos_Epochs_V1_QueryCurrentEpochRequest, Evmos_Epochs_V1_QueryCurrentEpochResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch.path, requestHandler: requestHandler)
  }

  public func enqueueCurrentEpochResponse(
    _ response: Evmos_Epochs_V1_QueryCurrentEpochResponse,
    _ requestHandler: @escaping (FakeRequestPart<Evmos_Epochs_V1_QueryCurrentEpochRequest>) -> () = { _ in }
  ) {
    let stream = self.makeCurrentEpochResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'CurrentEpoch'
  public var hasCurrentEpochResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Evmos_Epochs_V1_QueryClientMetadata.Methods.currentEpoch.path)
  }
}

