//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/slashing/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Msg defines the slashing Msg service.
///
/// Usage: instantiate `Cosmos_Slashing_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Slashing_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func unjail(
    _ request: Cosmos_Slashing_V1beta1_MsgUnjail,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse>

  func updateParams(
    _ request: Cosmos_Slashing_V1beta1_MsgUpdateParams,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse>
}

extension Cosmos_Slashing_V1beta1_MsgClientProtocol {
  public var serviceName: String {
    return "cosmos.slashing.v1beta1.Msg"
  }

  /// Unjail defines a method for unjailing a jailed validator, thus returning
  /// them into the bonded validator set, so they can begin receiving provisions
  /// and rewards again.
  ///
  /// - Parameters:
  ///   - request: Request to send to Unjail.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func unjail(
    _ request: Cosmos_Slashing_V1beta1_MsgUnjail,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnjailInterceptors() ?? []
    )
  }

  /// UpdateParams defines a governance operation for updating the x/slashing module
  /// parameters. The authority defaults to the x/gov module account.
  ///
  /// Since: cosmos-sdk 0.47
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateParams(
    _ request: Cosmos_Slashing_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse> {
    return self.makeUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Cosmos_Slashing_V1beta1_MsgClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Cosmos_Slashing_V1beta1_MsgNIOClient")
public final class Cosmos_Slashing_V1beta1_MsgClient: Cosmos_Slashing_V1beta1_MsgClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the cosmos.slashing.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Cosmos_Slashing_V1beta1_MsgNIOClient: Cosmos_Slashing_V1beta1_MsgClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.slashing.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Msg defines the slashing Msg service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Cosmos_Slashing_V1beta1_MsgAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func makeUnjailCall(
    _ request: Cosmos_Slashing_V1beta1_MsgUnjail,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse>

  func makeUpdateParamsCall(
    _ request: Cosmos_Slashing_V1beta1_MsgUpdateParams,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Slashing_V1beta1_MsgAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Cosmos_Slashing_V1beta1_MsgClientMetadata.serviceDescriptor
  }

  public var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeUnjailCall(
    _ request: Cosmos_Slashing_V1beta1_MsgUnjail,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnjailInterceptors() ?? []
    )
  }

  public func makeUpdateParamsCall(
    _ request: Cosmos_Slashing_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Cosmos_Slashing_V1beta1_MsgAsyncClientProtocol {
  public func unjail(
    _ request: Cosmos_Slashing_V1beta1_MsgUnjail,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Slashing_V1beta1_MsgUnjailResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnjailInterceptors() ?? []
    )
  }

  public func updateParams(
    _ request: Cosmos_Slashing_V1beta1_MsgUpdateParams,
    callOptions: CallOptions? = nil
  ) async throws -> Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Cosmos_Slashing_V1beta1_MsgAsyncClient: Cosmos_Slashing_V1beta1_MsgAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

public protocol Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'unjail'.
  func makeUnjailInterceptors() -> [ClientInterceptor<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse>]

  /// - Returns: Interceptors to use when invoking 'updateParams'.
  func makeUpdateParamsInterceptors() -> [ClientInterceptor<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse>]
}

public enum Cosmos_Slashing_V1beta1_MsgClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Msg",
    fullName: "cosmos.slashing.v1beta1.Msg",
    methods: [
      Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail,
      Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams,
    ]
  )

  public enum Methods {
    public static let unjail = GRPCMethodDescriptor(
      name: "Unjail",
      path: "/cosmos.slashing.v1beta1.Msg/Unjail",
      type: GRPCCallType.unary
    )

    public static let updateParams = GRPCMethodDescriptor(
      name: "UpdateParams",
      path: "/cosmos.slashing.v1beta1.Msg/UpdateParams",
      type: GRPCCallType.unary
    )
  }
}

#if compiler(>=5.6)
@available(swift, deprecated: 5.6)
extension Cosmos_Slashing_V1beta1_MsgTestClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(swift, deprecated: 5.6, message: "Test clients are not Sendable but the 'GRPCClient' API requires clients to be Sendable. Using a localhost client and server is the recommended alternative.")
public final class Cosmos_Slashing_V1beta1_MsgTestClient: Cosmos_Slashing_V1beta1_MsgClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Slashing_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the Unjail RPC. This must be called
  /// before calling 'unjail'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeUnjailResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_MsgUnjail>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Slashing_V1beta1_MsgUnjail, Cosmos_Slashing_V1beta1_MsgUnjailResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail.path, requestHandler: requestHandler)
  }

  public func enqueueUnjailResponse(
    _ response: Cosmos_Slashing_V1beta1_MsgUnjailResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_MsgUnjail>) -> () = { _ in }
  ) {
    let stream = self.makeUnjailResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'Unjail'
  public var hasUnjailResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.unjail.path)
  }

  /// Make a unary response for the UpdateParams RPC. This must be called
  /// before calling 'updateParams'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makeUpdateParamsResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_MsgUpdateParams>) -> () = { _ in }
  ) -> FakeUnaryResponse<Cosmos_Slashing_V1beta1_MsgUpdateParams, Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse> {
    return self.fakeChannel.makeFakeUnaryResponse(path: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams.path, requestHandler: requestHandler)
  }

  public func enqueueUpdateParamsResponse(
    _ response: Cosmos_Slashing_V1beta1_MsgUpdateParamsResponse,
    _ requestHandler: @escaping (FakeRequestPart<Cosmos_Slashing_V1beta1_MsgUpdateParams>) -> () = { _ in }
  ) {
    let stream = self.makeUpdateParamsResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'UpdateParams'
  public var hasUpdateParamsResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: Cosmos_Slashing_V1beta1_MsgClientMetadata.Methods.updateParams.path)
  }
}

